In [ ]:
import pandas as pd
import joblib
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
vpn_df = pd.read_csv("vpn.csv")
nonvpn_df = pd.read_csv("non vpn.csv")

In [ ]:
print(vpn_df.columns)
print(nonvpn_df.columns)

print(vpn_df["class1"].unique())
print(nonvpn_df["class1"].unique())

Index(['duration', 'total_fiat', 'total_biat', 'min_fiat', 'min_biat',
       'max_fiat', 'max_biat', 'mean_fiat', 'mean_biat', 'flowPktsPerSecond',
       'flowBytesPerSecond', 'min_flowiat', 'max_flowiat', 'mean_flowiat',
       'std_flowiat', 'min_active', 'mean_active', 'max_active', 'std_active',
       'min_idle', 'mean_idle', 'max_idle', 'std_idle', 'class1'],
      dtype='object')
Index(['duration', 'total_fiat', 'total_biat', 'min_fiat', 'min_biat',
       'max_fiat', 'max_biat', 'mean_fiat', 'mean_biat', 'flowPktsPerSecond',
       'flowBytesPerSecond', 'min_flowiat', 'max_flowiat', 'mean_flowiat',
       'std_flowiat', 'min_active', 'mean_active', 'max_active', 'std_active',
       'min_idle', 'mean_idle', 'max_idle', 'std_idle', 'class1'],
      dtype='object')
['VPN-BROWSING' 'VPN-CHAT' 'VPN-FT' 'VPN-MAIL' 'VPN-P2P' 'VPN-STREAMING'
 'VPN-VOIP']
['BROWSING' 'CHAT' 'FT' 'MAIL' 'P2P' 'STREAMING' 'VOIP']

In [ ]:
vpn_df["class1"] = vpn_df["class1"].str.strip().str.lower()
nonvpn_df["class1"] = nonvpn_df["class1"].str.strip().str.lower()

In [ ]:
nonvpn_df = nonvpn_df[vpn_df.columns]

In [ ]:
merged_df = pd.concat([vpn_df, nonvpn_df], ignore_index=True)

In [ ]:
merged_df = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
merged_df.to_csv("vpn_nonvpn_merged_final.csv", index=False)

In [ ]:
merged_df

,duration,total_fiat,total_biat,min_fiat,min_biat,max_fiat,max_biat,mean_fiat,mean_biat,flowPktsPerSecond,...,std_flowiat,min_active,mean_active,max_active,std_active,min_idle,mean_idle,max_idle,std_idle,class1
0,0,0,0,-1,-1,-1,-1,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,ft
1,2190899,2059586,2058989,283,26,708710,572435,1.716322e+05,1.211170e+05,14.149443,...,1.166032e+05,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,vpn-mail
2,14992148,14980103,14985392,14748,5675,25851,24904,2.000014e+04,2.000720e+04,100.052374,...,3.923415e+03,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,voip
3,14422647,14422129,14420995,959416,958897,962726,963028,9.614753e+05,9.613997e+05,2.218733,...,4.876608e+05,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,voip
4,14434537,14433838,14433779,961236,960088,963544,963580,9.622559e+05,9.622519e+05,2.216905,...,4.880674e+05,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,voip
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18753,3785728,3785728,122791,10,70,3688561,65722,3.441571e+05,1.364344e+04,5.811300,...,7.889826e+05,3771468,3.771468e+06,3771468,0.000000e+00,3622964,3.622964e+06,3622964,0.000000e+00,browsing
18754,349034,349034,212768,4,19,212620,176109,3.490340e+04,4.255360e+04,48.705857,...,5.370699e+04,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,browsing
18755,51418116,51418073,7632137,1208,283716,43785919,6587752,8.569679e+06,2.544046e+06,0.213932,...,1.370000e+07,7632137,2.570000e+07,43785979,2.560000e+07,6550968,2.520000e+07,43785919,2.630000e+07,vpn-ft
18756,2118759,2093527,2093369,15,9,1145544,1145493,7.219059e+04,5.105778e+04,33.982157,...,1.360107e+05,1783286,1.783286e+06,1783286,0.000000e+00,1120195,1.120195e+06,1120195,0.000000e+00,vpn-browsing
18757,14129167,14088624,14129167,2,6,3678917,3641605,6.852444e+03,8.200329e+03,267.602471,...,9.579941e+04,3798609,4.002137e+06,4205350,2.033707e+05,3190554,3.391428e+06,3641605,2.295317e+05,streaming

In [ ]:
import pandas as pd
import numpy as np
import joblib

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

In [ ]:
df = pd.read_csv("vpn_nonvpn_merged_final.csv")

In [ ]:
print(df.shape)
print(df.isnull().sum())
print(df["class1"].unique())

(18758, 24)
duration              0
total_fiat            0
total_biat            0
min_fiat              0
min_biat              0
max_fiat              0
max_biat              0
mean_fiat             0
mean_biat             0
flowPktsPerSecond     0
flowBytesPerSecond    0
min_flowiat           0
max_flowiat           0
mean_flowiat          0
std_flowiat           0
min_active            0
mean_active           0
max_active            0
std_active            0
min_idle              0
mean_idle             0
max_idle              0
std_idle              0
class1                0
dtype: int64
['ft' 'vpn-mail' 'voip' 'p2p' 'vpn-ft' 'chat' 'vpn-voip' 'browsing'
 'vpn-p2p' 'vpn-streaming' 'vpn-chat' 'vpn-browsing' 'mail' 'streaming']

In [ ]:
import pandas as pd

# Count samples per class
class_counts = df['class1'].value_counts()
print(class_counts)

class1
voip             2826
browsing         2500
vpn-browsing     2500
vpn-voip         2271
vpn-ft           1932
vpn-chat         1196
ft               1018
p2p              1000
vpn-p2p           928
chat              890
vpn-mail          491
streaming         482
vpn-streaming     475
mail              249
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [ ]:
# ----------------------------
# 1. Separate features and target
# ----------------------------
X = df.drop('class1', axis=1)  # numeric features
y = df['class1']               # target labels (strings)

In [ ]:
# ----------------------------
# 2. Apply SMOTE to balance classes
# ----------------------------
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

print("\nBefore SMOTE:\n", class_counts)
print("\nAfter SMOTE:\n", pd.Series(y_res).value_counts())

Before SMOTE:
 class1
voip             2826
browsing         2500
vpn-browsing     2500
vpn-voip         2271
vpn-ft           1932
vpn-chat         1196
ft               1018
p2p              1000
vpn-p2p           928
chat              890
vpn-mail          491
streaming         482
vpn-streaming     475
mail              249
Name: count, dtype: int64

After SMOTE:
 class1
ft               2826
vpn-mail         2826
voip             2826
p2p              2826
vpn-ft           2826
chat             2826
vpn-voip         2826
browsing         2826
vpn-p2p          2826
vpn-streaming    2826
vpn-chat         2826
vpn-browsing     2826
mail             2826
streaming        2826
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
import joblib

# ----------------------------
# Label encode the target
# ----------------------------
le = LabelEncoder()
y_res_enc = le.fit_transform(y_res)  # numeric labels

# ----------------------------
# Print the mapping of classes → numbers
# ----------------------------
print("Class → Encoded Label Mapping:")
for cls, enc in zip(le.classes_, range(len(le.classes_))):
    print(f"{cls} → {enc}")

# ----------------------------
# Save the LabelEncoder for later
# ----------------------------
joblib.dump(le, 'label_encoder.pkl')
print("\nLabelEncoder saved as 'label_encoder.pkl'")

Class → Encoded Label Mapping:
browsing → 0
chat → 1
ft → 2
mail → 3
p2p → 4
streaming → 5
voip → 6
vpn-browsing → 7
vpn-chat → 8
vpn-ft → 9
vpn-mail → 10
vpn-p2p → 11
vpn-streaming → 12
vpn-voip → 13

LabelEncoder saved as 'label_encoder.pkl'

In [ ]:
# ----------------------------
# 4. Split into train/test sets
# ----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res_enc, test_size=0.2, random_state=42, stratify=y_res_enc
)

In [45]:
X_train

,duration,total_fiat,total_biat,min_fiat,min_biat,max_fiat,max_biat,mean_fiat,mean_biat,flowPktsPerSecond,...,mean_flowiat,std_flowiat,min_active,mean_active,max_active,std_active,min_idle,mean_idle,max_idle,std_idle
28737,12706855,12652814,12682226,3,3,3182556,3134017,1.367650e+04,1.693867e+04,134.608187,...,7.558351e+03,1.197289e+05,3359308,4.004750e+06,4757974,7.237204e+05,2326554,2.817321e+06,3128352,4.519872e+05
20959,14469913,14396442,14468707,47,40,3851507,3902928,4.093404e+05,5.522766e+05,4.381432,...,2.319950e+05,7.435041e+05,1196716,2.832908e+06,4997039,1.441104e+06,1078229,2.520555e+06,3851507,1.093809e+06
36028,0,0,0,-1,-1,-1,-1,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00
25995,13093957,13093781,13093778,1371487,1275220,7021019,7021007,3.879901e+06,3.879900e+06,0.693677,...,1.685918e+06,2.596255e+06,2399699,4.364592e+06,7021015,2.462439e+06,2217513,4.281450e+06,7020829,2.555141e+06
30822,14503413,14464877,14503325,24,26,6315910,6092691,2.651157e+05,2.354119e+05,8.183961,...,1.237798e+05,6.175068e+05,2056452,4.276645e+06,6386958,2.160663e+06,1438065,3.309013e+06,6092676,2.454373e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8274,14978171,14978171,14477847,64,382,84657,487706,3.025893e+04,3.290420e+05,36.119230,...,2.773735e+04,1.487824e+04,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00
17313,0,0,0,-1,-1,-1,-1,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00
30508,14810446,14810443,14186244,22011,108595,5239890,5441393,1.030477e+06,1.259987e+06,2.728401,...,5.532611e+05,1.272571e+06,5937083,6.597055e+06,7257025,9.333398e+05,5063276,5.119536e+06,5175796,7.956359e+04
29683,747631,567752,601276,48,22,147604,180527,5.352393e+03,2.853732e+03,975.141262,...,2.409450e+03,1.430733e+04,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00,-1,0.000000e+00
8529,3600762,3535156,3575156,16,33,3365268,3391178,3.927951e+05,5.958593e+05,4.721223,...,2.250476e+05,8.380193e+05,3390906,3.390906e+06,3390906,0.000000e+00,3365268,3.365268e+06,3365268,0.000000e+00

In [47]:
y_train

array([ 5,  1, 11, ...,  8,  7,  7])

In [48]:
y_res_enc

array([ 2, 10,  6, ..., 13, 13, 13])

In [ ]:
# ----------------------------
# 5. Train XGBoost Classifier
# ----------------------------
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
xgb_clf.fit(X_train, y_train)
y_pred_xgb = xgb_clf.predict(X_test)

print("\nXGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgb, target_names=le.classes_))

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [09:14:29] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBoost Classification Report:
               precision    recall  f1-score   support

     browsing       0.86      0.87      0.86       565
         chat       0.91      0.91      0.91       565
           ft       0.94      0.77      0.85       565
         mail       0.90      0.97      0.93       566
          p2p       0.95      0.97      0.96       565
    streaming       0.94      0.89      0.91       565
         voip       1.00      0.99      0.99       566
 vpn-browsing       0.86      0.86      0.86       565
     vpn-chat       0.85      0.82      0.83       565
       vpn-ft       0.89      0.83      0.86       565
     vpn-mail       0.92      0.90      0.91       566
      vpn-p2p       0.72      0.89      0.80       565
vpn-streaming       0.96      0.98      0.97       565
     vpn-voip       1.00      0.98      0.99       565

     accuracy                           0.90      7913
    macro avg       0.91      0.90      0.90      7913
 weighted avg       0.91      0.90      0.90      7913

In [ ]:
# ----------------------------
# 6. Train Random Forest Classifier
# ----------------------------


rf_clf = RandomForestClassifier(n_estimators=5, random_state=42)
rf_clf.fit(X_train, y_train)
y_pred_rf = rf_clf.predict(X_test)

print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf, target_names=le.classes_))

Random Forest Classification Report:
               precision    recall  f1-score   support

     browsing       0.73      0.82      0.78       565
         chat       0.82      0.89      0.85       565
           ft       0.89      0.75      0.82       565
         mail       0.90      0.94      0.92       566
          p2p       0.93      0.95      0.94       565
    streaming       0.90      0.87      0.88       565
         voip       0.99      0.99      0.99       566
 vpn-browsing       0.80      0.76      0.78       565
     vpn-chat       0.78      0.74      0.76       565
       vpn-ft       0.84      0.74      0.79       565
     vpn-mail       0.90      0.87      0.89       566
      vpn-p2p       0.70      0.84      0.76       565
vpn-streaming       0.96      0.96      0.96       565
     vpn-voip       0.99      0.97      0.98       565

     accuracy                           0.86      7913
    macro avg       0.87      0.86      0.86      7913
 weighted avg       0.87      0.86      0.86      7913

In [ ]:
import joblib
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

# ----------------------------
# 1. Save the trained models
# ----------------------------
joblib.dump(xgb_clf, 'xgb_vpn_model.pkl')
print("XGBoost model saved as 'xgb_vpn_model.pkl'")

joblib.dump(rf_clf, 'rf_vpn_model.pkl')
print("Random Forest model saved as 'rf_vpn_model.pkl'")

# ----------------------------
# 2. Save the LabelEncoder
# ----------------------------
joblib.dump(le, 'label_encoder.pkl')
print("LabelEncoder saved as 'label_encoder.pkl'")

# ----------------------------
# 3. Optional: Save class mapping
# ----------------------------
class_mapping = dict(zip(le.classes_, range(len(le.classes_))))
joblib.dump(class_mapping, 'class_mapping.pkl')
print("Class mapping saved as 'class_mapping.pkl'")
print("Class → Label mapping:", class_mapping)

XGBoost model saved as 'xgb_vpn_model.pkl'
Random Forest model saved as 'rf_vpn_model.pkl'
LabelEncoder saved as 'label_encoder.pkl'
Class mapping saved as 'class_mapping.pkl'
Class → Label mapping: {'browsing': 0, 'chat': 1, 'ft': 2, 'mail': 3, 'p2p': 4, 'streaming': 5, 'voip': 6, 'vpn-browsing': 7, 'vpn-chat': 8, 'vpn-ft': 9, 'vpn-mail': 10, 'vpn-p2p': 11, 'vpn-streaming': 12, 'vpn-voip': 13}

In [ ]:
a

In [49]:
import gradio as gr
import pandas as pd
import joblib
import numpy as np

# ----------------------------
# 1. Load saved model, encoder, and dataset
# ----------------------------
xgb_model = joblib.load('xgb_vpn_model.pkl')   # XGBoost model
le = joblib.load('label_encoder.pkl')          # LabelEncoder
df = pd.read_csv("/content/vpn_nonvpn_merged_final.csv")            # Your dataset with all features + 'class1'

feature_names = [col for col in df.columns if col != 'class1']

# ----------------------------
# 2. Prediction function
# ----------------------------
def predict_random_sample():
    # Pick a random row from the dataset
    sample = df.sample(1, random_state=np.random.randint(0, 1000))

    X_input = sample[feature_names]

    # Predict encoded label
    y_pred_enc = xgb_model.predict(X_input)

    # Convert numeric label back to class name
    y_pred_label = le.inverse_transform(y_pred_enc)

    # Return features, true class, and predicted class
    return X_input.values[0], sample['class1'].values[0], y_pred_label[0]

# ----------------------------
# 3. Build Gradio Interface
# ----------------------------
iface = gr.Interface(
    fn=predict_random_sample,
    inputs=[],
    outputs=[
        gr.Dataframe(headers=feature_names, label="Random Sample Features"),
        gr.Textbox(label="True Class"),
        gr.Textbox(label="Predicted Class")
    ],
    title="VPN Traffic Classifier - Random Sample",
    description="Click submit to see a random sample from the dataset and its predicted VPN traffic class."
)

# ----------------------------
# 4. Launch the app
# ----------------------------
iface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://21379e245b9ae8265a.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [30]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Conv1D, MaxPooling1D, Flatten, Dropout
from tensorflow.keras.utils import to_categorical

In [32]:
# Convert X_res to NumPy array
X_res_np = X_res.values  # pandas DataFrame → NumPy array

# Reshape for LSTM/CNN: (samples, timesteps=1, features)
X_res_3d = X_res_np.reshape((X_res_np.shape[0], 1, X_res_np.shape[1]))

# One-hot encode target for deep learning
y_res_cat = to_categorical(y_res_enc)

# Split into train/test
X_train_dl, X_test_dl, y_train_dl, y_test_dl = train_test_split(
    X_res_3d, y_res_cat, test_size=0.2, random_state=42, stratify=y_res_enc
)

In [38]:
X_res_np

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00, -1.0000000e+00,  0.0000000e+00],
       [ 2.1908990e+06,  2.0595860e+06,  2.0589890e+06, ...,
         0.0000000e+00, -1.0000000e+00,  0.0000000e+00],
       [ 1.4992148e+07,  1.4980103e+07,  1.4985392e+07, ...,
         0.0000000e+00, -1.0000000e+00,  0.0000000e+00],
       ...,
       [ 1.0077309e+07,  1.0038669e+07,  1.0038920e+07, ...,
         1.0000000e+07,  1.0000279e+07,  0.0000000e+00],
       [ 1.4445367e+07,  1.4406175e+07,  1.4406403e+07, ...,
         0.0000000e+00, -1.0000000e+00,  0.0000000e+00],
       [ 1.4999206e+07,  1.4981082e+07,  1.4982661e+07, ...,
         0.0000000e+00, -1.0000000e+00,  0.0000000e+00]])

In [53]:
from tensorflow.keras.layers import Bidirectional

lstm_model = Sequential([
    Bidirectional(
        LSTM(128, return_sequences=True),
        input_shape=(X_train_dl.shape[1], X_train_dl.shape[2])
    ),
    Dropout(0.3),

    Bidirectional(LSTM(64)),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(y_train_dl.shape[1], activation='softmax')
])

lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

lstm_model.summary()

history_lstm = lstm_model.fit(
    X_train_dl, y_train_dl,
    validation_data=(X_test_dl, y_test_dl),
    epochs=30,
    batch_size=32
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)   │ (None, 1, 256)         │       155,648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 1, 256)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 128)            │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 14)             │           910 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 329,166 (1.26 MB)

 Trainable params: 329,166 (1.26 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.2679 - loss: 2.1354 - val_accuracy: 0.3651 - val_loss: 1.7499
Epoch 2/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3226 - loss: 1.8698 - val_accuracy: 0.3746 - val_loss: 1.7117
Epoch 3/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.3290 - loss: 1.8414 - val_accuracy: 0.3815 - val_loss: 1.6866
Epoch 4/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 20s 13ms/step - accuracy: 0.3457 - loss: 1.7970 - val_accuracy: 0.4002 - val_loss: 1.6343
Epoch 5/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 21s 13ms/step - accuracy: 0.3540 - loss: 1.7591 - val_accuracy: 0.4175 - val_loss: 1.5919
Epoch 6/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3681 - loss: 1.7276 - val_accuracy: 0.3942 - val_loss: 1.6229
Epoch 7/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.3632 - loss: 1.7304 - val_accuracy: 0.3868 - val_loss: 1.6758
Epoch 8/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3437 - loss: 1.7816 - val_accuracy: 0.3780 - val_loss: 1.6501
Epoch 9/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3639 - loss: 1.7615 - val_accuracy: 0.3971 - val_loss: 1.6311
Epoch 10/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3564 - loss: 1.7543 - val_accuracy: 0.4082 - val_loss: 1.6039
Epoch 11/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3642 - loss: 1.7424 - val_accuracy: 0.3871 - val_loss: 1.6539
Epoch 12/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3586 - loss: 1.7423 - val_accuracy: 0.3880 - val_loss: 1.6579
Epoch 13/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3460 - loss: 1.7886 - val_accuracy: 0.3885 - val_loss: 1.6406
Epoch 14/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3546 - loss: 1.7597 - val_accuracy: 0.3966 - val_loss: 1.6313
Epoch 15/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 21s 13ms/step - accuracy: 0.3539 - loss: 1.7754 - val_accuracy: 0.3762 - val_loss: 1.6543
Epoch 16/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3507 - loss: 1.7534 - val_accuracy: 0.3915 - val_loss: 1.6329
Epoch 17/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3649 - loss: 1.7379 - val_accuracy: 0.3906 - val_loss: 1.6156
Epoch 18/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3530 - loss: 1.7434 - val_accuracy: 0.4030 - val_loss: 1.6401
Epoch 19/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3645 - loss: 1.7398 - val_accuracy: 0.3913 - val_loss: 1.5974
Epoch 20/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - accuracy: 0.3610 - loss: 1.7377 - val_accuracy: 0.4053 - val_loss: 1.6256
Epoch 21/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3545 - loss: 1.7582 - val_accuracy: 0.3880 - val_loss: 1.6356
Epoch 22/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3623 - loss: 1.7400 - val_accuracy: 0.4026 - val_loss: 1.5807
Epoch 23/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.3621 - loss: 1.7355 - val_accuracy: 0.3962 - val_loss: 1.5828
Epoch 24/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3625 - loss: 1.7211 - val_accuracy: 0.3935 - val_loss: 1.5919
Epoch 25/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3675 - loss: 1.7167 - val_accuracy: 0.4192 - val_loss: 1.5511
Epoch 26/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3721 - loss: 1.6893 - val_accuracy: 0.4073 - val_loss: 1.5716
Epoch 27/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - accuracy: 0.3671 - loss: 1.7335 - val_accuracy: 0.3913 - val_loss: 1.6124
Epoch 28/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 20s 13ms/step - accuracy: 0.3658 - loss: 1.7077 - val_accuracy: 0.4010 - val_loss: 1.6145
Epoch 29/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 13s 13ms/step - accuracy: 0.3563 - loss: 1.7472 - val_accuracy: 0.3966 - val_loss: 1.6129
Epoch 30/30
990/990 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.3559 - loss: 1.7364 - val_accuracy: 0.3882 - val_loss: 1.6237

In [51]:
cnn_model = Sequential([
    Conv1D(64, kernel_size=1, activation='relu', input_shape=(X_train_dl.shape[1], X_train_dl.shape[2])),
    MaxPooling1D(pool_size=1),
    Dropout(0.2),
    Flatten(),
    Dense(32, activation='relu'),
    Dense(y_train_dl.shape[1], activation='softmax')
])

cnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn_model.summary()

# Train CNN
history_cnn = cnn_model.fit(
    X_train_dl, y_train_dl,
    validation_data=(X_test_dl, y_test_dl),
    epochs=20, batch_size=32
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 1, 64)          │         1,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 1, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 1, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 14)             │           462 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,078 (15.93 KB)

 Trainable params: 4,078 (15.93 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.0932 - loss: 414855.5938 - val_accuracy: 0.0963 - val_loss: 4327.2988
Epoch 2/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.1007 - loss: 4435.2583 - val_accuracy: 0.0915 - val_loss: 2.5946
Epoch 3/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0870 - loss: 588.4844 - val_accuracy: 0.0915 - val_loss: 2.5886
Epoch 4/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0928 - loss: 161.7234 - val_accuracy: 0.0915 - val_loss: 2.5870
Epoch 5/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0934 - loss: 114.1144 - val_accuracy: 0.0917 - val_loss: 2.5864
Epoch 6/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0899 - loss: 99.7160 - val_accuracy: 0.0917 - val_loss: 2.5860
Epoch 7/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0925 - loss: 31.0070 - val_accuracy: 0.0919 - val_loss: 2.5864
Epoch 8/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.0896 - loss: 8.7796 - val_accuracy: 0.0919 - val_loss: 2.5858
Epoch 9/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0941 - loss: 6.9778 - val_accuracy: 0.0917 - val_loss: 2.5857
Epoch 10/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0904 - loss: 27.4335 - val_accuracy: 0.0919 - val_loss: 2.5853
Epoch 11/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0889 - loss: 10.6668 - val_accuracy: 0.0919 - val_loss: 2.5860
Epoch 12/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0925 - loss: 12.9548 - val_accuracy: 0.0919 - val_loss: 2.5847
Epoch 13/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0922 - loss: 9.1235 - val_accuracy: 0.0919 - val_loss: 2.5853
Epoch 14/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0921 - loss: 2.8162 - val_accuracy: 0.0915 - val_loss: 2.5849
Epoch 15/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0869 - loss: 3.7931 - val_accuracy: 0.0915 - val_loss: 2.5849
Epoch 16/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0889 - loss: 3.0988 - val_accuracy: 0.0919 - val_loss: 2.5856
Epoch 17/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0909 - loss: 25.0643 - val_accuracy: 0.0919 - val_loss: 2.5850
Epoch 18/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0958 - loss: 3.5087 - val_accuracy: 0.0919 - val_loss: 2.5847
Epoch 19/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0899 - loss: 2.6108 - val_accuracy: 0.0919 - val_loss: 2.5849
Epoch 20/20
990/990 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0895 - loss: 2.5849 - val_accuracy: 0.0919 - val_loss: 2.5856

In [54]:
from sklearn.metrics import classification_report
import numpy as np

# LSTM
y_pred_lstm = lstm_model.predict(X_test_dl)
y_pred_labels_lstm = np.argmax(y_pred_lstm, axis=1)
y_true_labels = np.argmax(y_test_dl, axis=1)

print("\nLSTM Classification Report:")
print(classification_report(y_true_labels, y_pred_labels_lstm, target_names=le.classes_))

# CNN
y_pred_cnn = cnn_model.predict(X_test_dl)
y_pred_labels_cnn = np.argmax(y_pred_cnn, axis=1)

print("\nCNN Classification Report:")
print(classification_report(y_true_labels, y_pred_labels_cnn, target_names=le.classes_))

248/248 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step

LSTM Classification Report:
               precision    recall  f1-score   support

     browsing       0.25      0.23      0.24       565
         chat       0.33      0.25      0.29       565
           ft       0.80      0.11      0.19       565
         mail       0.36      0.60      0.45       566
          p2p       0.35      0.43      0.39       565
    streaming       0.45      0.21      0.28       565
         voip       0.43      0.84      0.57       566
 vpn-browsing       0.36      0.46      0.41       565
     vpn-chat       0.49      0.20      0.28       565
       vpn-ft       0.44      0.24      0.31       565
     vpn-mail       0.26      0.46      0.33       566
      vpn-p2p       0.55      0.39      0.45       565
vpn-streaming       0.43      0.45      0.44       565
     vpn-voip       0.52      0.56      0.54       565

     accuracy                           0.39      7913
    macro avg       0.43      0.39      0.37      7913
 weighted avg       0.43      0.39      0.37      7913

248/248 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

CNN Classification Report:
               precision    recall  f1-score   support

     browsing       0.00      0.00      0.00       565
         chat       0.00      0.00      0.00       565
           ft       0.00      0.00      0.00       565
         mail       0.00      0.00      0.00       566
          p2p       0.00      0.00      0.00       565
    streaming       0.00      0.00      0.00       565
         voip       0.00      0.00      0.00       566
 vpn-browsing       0.00      0.00      0.00       565
     vpn-chat       0.00      0.00      0.00       565
       vpn-ft       0.00      0.00      0.00       565
     vpn-mail       0.00      0.00      0.00       566
      vpn-p2p       0.51      0.29      0.37       565
vpn-streaming       0.07      1.00      0.14       565
     vpn-voip       0.00      0.00      0.00       565

     accuracy                           0.09      7913
    macro avg       0.04      0.09      0.04      7913
 weighted avg       0.04      0.09      0.04      7913

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))